### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by bnhovde** [alfrcr/predatorjs#1]
Hi, loving this library. There's a serious need for simple, clean validation libraries for React out there and yours is the best one I've found so far.

The only issue I can see is my project size taking a hit by including the entire lodash library.

A couple of suggestions:

1: Only include the lodash functions that are used in the project. (see [this post](https://lacke.mn/reduce-your-bundle-js-file-size/) for example)
2: Use es5/6. It looks like most of the lodash functions used can be swapped for vanilla variants, maybe aside from Object.assign.

Thanks for the good work!

**Comment by alfrcr** [comment]
Will work on it. Btw thanks for all your suggestions (on twitter too).

**Comment by bnhovde** [comment]
No problems! 👍  I'm using this lib in a project so I'll log things as I spot them.

**Comment by bnhovde** [comment]
Awesome! Removed off 50Kb from build size in by app!

**Comment by alfrcr** [comment]
Great!
I have added new validation rule as well 👍
